global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'forum-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['forum-service:8081']

  - job_name: 'study-management-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['study-management-1:8082', 'study-management-2:8082']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']
